/*
 * Zipper Auth API
 * Authentication, OAuth, API keys, and partner/merchant onboarding endpoints exposed via the gateway.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.zipper.auth.sdk.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.zipper.auth.sdk.JSON;

/**
 * IntrospectionResponse
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.13.0")
public class IntrospectionResponse {
  public static final String SERIALIZED_NAME_ACTIVE = "active";
  @SerializedName(SERIALIZED_NAME_ACTIVE)
  @javax.annotation.Nullable
  private Boolean active;

  public static final String SERIALIZED_NAME_SCOPE = "scope";
  @SerializedName(SERIALIZED_NAME_SCOPE)
  @javax.annotation.Nullable
  private String scope;

  public static final String SERIALIZED_NAME_SUB = "sub";
  @SerializedName(SERIALIZED_NAME_SUB)
  @javax.annotation.Nullable
  private String sub;

  public static final String SERIALIZED_NAME_EXP = "exp";
  @SerializedName(SERIALIZED_NAME_EXP)
  @javax.annotation.Nullable
  private Long exp;

  public static final String SERIALIZED_NAME_IAT = "iat";
  @SerializedName(SERIALIZED_NAME_IAT)
  @javax.annotation.Nullable
  private Long iat;

  public static final String SERIALIZED_NAME_ISS = "iss";
  @SerializedName(SERIALIZED_NAME_ISS)
  @javax.annotation.Nullable
  private String iss;

  public static final String SERIALIZED_NAME_AZP = "azp";
  @SerializedName(SERIALIZED_NAME_AZP)
  @javax.annotation.Nullable
  private String azp;

  public static final String SERIALIZED_NAME_JTI = "jti";
  @SerializedName(SERIALIZED_NAME_JTI)
  @javax.annotation.Nullable
  private String jti;

  public static final String SERIALIZED_NAME_TOKEN_TYPE = "token_type";
  @SerializedName(SERIALIZED_NAME_TOKEN_TYPE)
  @javax.annotation.Nullable
  private String tokenType;

  public static final String SERIALIZED_NAME_AUTH_METHOD = "auth_method";
  @SerializedName(SERIALIZED_NAME_AUTH_METHOD)
  @javax.annotation.Nullable
  private String authMethod;

  public static final String SERIALIZED_NAME_CLIENT_ID = "client_id";
  @SerializedName(SERIALIZED_NAME_CLIENT_ID)
  @javax.annotation.Nullable
  private String clientId;

  public IntrospectionResponse() {
  }

  public IntrospectionResponse active(@javax.annotation.Nullable Boolean active) {
    this.active = active;
    return this;
  }

  /**
   * Get active
   * @return active
   */
  @javax.annotation.Nullable
  public Boolean getActive() {
    return active;
  }

  public void setActive(@javax.annotation.Nullable Boolean active) {
    this.active = active;
  }


  public IntrospectionResponse scope(@javax.annotation.Nullable String scope) {
    this.scope = scope;
    return this;
  }

  /**
   * Get scope
   * @return scope
   */
  @javax.annotation.Nullable
  public String getScope() {
    return scope;
  }

  public void setScope(@javax.annotation.Nullable String scope) {
    this.scope = scope;
  }


  public IntrospectionResponse sub(@javax.annotation.Nullable String sub) {
    this.sub = sub;
    return this;
  }

  /**
   * Get sub
   * @return sub
   */
  @javax.annotation.Nullable
  public String getSub() {
    return sub;
  }

  public void setSub(@javax.annotation.Nullable String sub) {
    this.sub = sub;
  }


  public IntrospectionResponse exp(@javax.annotation.Nullable Long exp) {
    this.exp = exp;
    return this;
  }

  /**
   * Get exp
   * @return exp
   */
  @javax.annotation.Nullable
  public Long getExp() {
    return exp;
  }

  public void setExp(@javax.annotation.Nullable Long exp) {
    this.exp = exp;
  }


  public IntrospectionResponse iat(@javax.annotation.Nullable Long iat) {
    this.iat = iat;
    return this;
  }

  /**
   * Get iat
   * @return iat
   */
  @javax.annotation.Nullable
  public Long getIat() {
    return iat;
  }

  public void setIat(@javax.annotation.Nullable Long iat) {
    this.iat = iat;
  }


  public IntrospectionResponse iss(@javax.annotation.Nullable String iss) {
    this.iss = iss;
    return this;
  }

  /**
   * Get iss
   * @return iss
   */
  @javax.annotation.Nullable
  public String getIss() {
    return iss;
  }

  public void setIss(@javax.annotation.Nullable String iss) {
    this.iss = iss;
  }


  public IntrospectionResponse azp(@javax.annotation.Nullable String azp) {
    this.azp = azp;
    return this;
  }

  /**
   * Get azp
   * @return azp
   */
  @javax.annotation.Nullable
  public String getAzp() {
    return azp;
  }

  public void setAzp(@javax.annotation.Nullable String azp) {
    this.azp = azp;
  }


  public IntrospectionResponse jti(@javax.annotation.Nullable String jti) {
    this.jti = jti;
    return this;
  }

  /**
   * Get jti
   * @return jti
   */
  @javax.annotation.Nullable
  public String getJti() {
    return jti;
  }

  public void setJti(@javax.annotation.Nullable String jti) {
    this.jti = jti;
  }


  public IntrospectionResponse tokenType(@javax.annotation.Nullable String tokenType) {
    this.tokenType = tokenType;
    return this;
  }

  /**
   * Get tokenType
   * @return tokenType
   */
  @javax.annotation.Nullable
  public String getTokenType() {
    return tokenType;
  }

  public void setTokenType(@javax.annotation.Nullable String tokenType) {
    this.tokenType = tokenType;
  }


  public IntrospectionResponse authMethod(@javax.annotation.Nullable String authMethod) {
    this.authMethod = authMethod;
    return this;
  }

  /**
   * Get authMethod
   * @return authMethod
   */
  @javax.annotation.Nullable
  public String getAuthMethod() {
    return authMethod;
  }

  public void setAuthMethod(@javax.annotation.Nullable String authMethod) {
    this.authMethod = authMethod;
  }


  public IntrospectionResponse clientId(@javax.annotation.Nullable String clientId) {
    this.clientId = clientId;
    return this;
  }

  /**
   * Get clientId
   * @return clientId
   */
  @javax.annotation.Nullable
  public String getClientId() {
    return clientId;
  }

  public void setClientId(@javax.annotation.Nullable String clientId) {
    this.clientId = clientId;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IntrospectionResponse introspectionResponse = (IntrospectionResponse) o;
    return Objects.equals(this.active, introspectionResponse.active) &&
        Objects.equals(this.scope, introspectionResponse.scope) &&
        Objects.equals(this.sub, introspectionResponse.sub) &&
        Objects.equals(this.exp, introspectionResponse.exp) &&
        Objects.equals(this.iat, introspectionResponse.iat) &&
        Objects.equals(this.iss, introspectionResponse.iss) &&
        Objects.equals(this.azp, introspectionResponse.azp) &&
        Objects.equals(this.jti, introspectionResponse.jti) &&
        Objects.equals(this.tokenType, introspectionResponse.tokenType) &&
        Objects.equals(this.authMethod, introspectionResponse.authMethod) &&
        Objects.equals(this.clientId, introspectionResponse.clientId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(active, scope, sub, exp, iat, iss, azp, jti, tokenType, authMethod, clientId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IntrospectionResponse {\n");
    sb.append("    active: ").append(toIndentedString(active)).append("\n");
    sb.append("    scope: ").append(toIndentedString(scope)).append("\n");
    sb.append("    sub: ").append(toIndentedString(sub)).append("\n");
    sb.append("    exp: ").append(toIndentedString(exp)).append("\n");
    sb.append("    iat: ").append(toIndentedString(iat)).append("\n");
    sb.append("    iss: ").append(toIndentedString(iss)).append("\n");
    sb.append("    azp: ").append(toIndentedString(azp)).append("\n");
    sb.append("    jti: ").append(toIndentedString(jti)).append("\n");
    sb.append("    tokenType: ").append(toIndentedString(tokenType)).append("\n");
    sb.append("    authMethod: ").append(toIndentedString(authMethod)).append("\n");
    sb.append("    clientId: ").append(toIndentedString(clientId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("active");
    openapiFields.add("scope");
    openapiFields.add("sub");
    openapiFields.add("exp");
    openapiFields.add("iat");
    openapiFields.add("iss");
    openapiFields.add("azp");
    openapiFields.add("jti");
    openapiFields.add("token_type");
    openapiFields.add("auth_method");
    openapiFields.add("client_id");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to IntrospectionResponse
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!IntrospectionResponse.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in IntrospectionResponse is not found in the empty JSON string", IntrospectionResponse.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!IntrospectionResponse.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `IntrospectionResponse` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("scope") != null && !jsonObj.get("scope").isJsonNull()) && !jsonObj.get("scope").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `scope` to be a primitive type in the JSON string but got `%s`", jsonObj.get("scope").toString()));
      }
      if ((jsonObj.get("sub") != null && !jsonObj.get("sub").isJsonNull()) && !jsonObj.get("sub").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `sub` to be a primitive type in the JSON string but got `%s`", jsonObj.get("sub").toString()));
      }
      if ((jsonObj.get("iss") != null && !jsonObj.get("iss").isJsonNull()) && !jsonObj.get("iss").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `iss` to be a primitive type in the JSON string but got `%s`", jsonObj.get("iss").toString()));
      }
      if ((jsonObj.get("azp") != null && !jsonObj.get("azp").isJsonNull()) && !jsonObj.get("azp").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `azp` to be a primitive type in the JSON string but got `%s`", jsonObj.get("azp").toString()));
      }
      if ((jsonObj.get("jti") != null && !jsonObj.get("jti").isJsonNull()) && !jsonObj.get("jti").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `jti` to be a primitive type in the JSON string but got `%s`", jsonObj.get("jti").toString()));
      }
      if ((jsonObj.get("token_type") != null && !jsonObj.get("token_type").isJsonNull()) && !jsonObj.get("token_type").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `token_type` to be a primitive type in the JSON string but got `%s`", jsonObj.get("token_type").toString()));
      }
      if ((jsonObj.get("auth_method") != null && !jsonObj.get("auth_method").isJsonNull()) && !jsonObj.get("auth_method").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `auth_method` to be a primitive type in the JSON string but got `%s`", jsonObj.get("auth_method").toString()));
      }
      if ((jsonObj.get("client_id") != null && !jsonObj.get("client_id").isJsonNull()) && !jsonObj.get("client_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `client_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("client_id").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!IntrospectionResponse.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'IntrospectionResponse' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<IntrospectionResponse> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(IntrospectionResponse.class));

       return (TypeAdapter<T>) new TypeAdapter<IntrospectionResponse>() {
           @Override
           public void write(JsonWriter out, IntrospectionResponse value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public IntrospectionResponse read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of IntrospectionResponse given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of IntrospectionResponse
   * @throws IOException if the JSON string is invalid with respect to IntrospectionResponse
   */
  public static IntrospectionResponse fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, IntrospectionResponse.class);
  }

  /**
   * Convert an instance of IntrospectionResponse to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

