/*
 * Zipper Auth API
 * Authentication, OAuth, API keys, and partner/merchant onboarding endpoints exposed via the gateway.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.zipper.auth.sdk.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.UUID;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.zipper.auth.sdk.JSON;

/**
 * Full merchant profile for the detail view
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.13.0")
public class MerchantDetail {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  @javax.annotation.Nullable
  private UUID id;

  public static final String SERIALIZED_NAME_NAME_HE = "nameHe";
  @SerializedName(SERIALIZED_NAME_NAME_HE)
  @javax.annotation.Nullable
  private String nameHe;

  public static final String SERIALIZED_NAME_NAME_EN = "nameEn";
  @SerializedName(SERIALIZED_NAME_NAME_EN)
  @javax.annotation.Nullable
  private String nameEn;

  public static final String SERIALIZED_NAME_BUSINESS_NAME = "businessName";
  @SerializedName(SERIALIZED_NAME_BUSINESS_NAME)
  @javax.annotation.Nullable
  private String businessName;

  public static final String SERIALIZED_NAME_OWNER_HE = "ownerHe";
  @SerializedName(SERIALIZED_NAME_OWNER_HE)
  @javax.annotation.Nullable
  private String ownerHe;

  public static final String SERIALIZED_NAME_OWNER_EN = "ownerEn";
  @SerializedName(SERIALIZED_NAME_OWNER_EN)
  @javax.annotation.Nullable
  private String ownerEn;

  public static final String SERIALIZED_NAME_EMAIL = "email";
  @SerializedName(SERIALIZED_NAME_EMAIL)
  @javax.annotation.Nullable
  private String email;

  public static final String SERIALIZED_NAME_BUSINESS_EMAIL = "businessEmail";
  @SerializedName(SERIALIZED_NAME_BUSINESS_EMAIL)
  @javax.annotation.Nullable
  private String businessEmail;

  public static final String SERIALIZED_NAME_BUSINESS_PHONE = "businessPhone";
  @SerializedName(SERIALIZED_NAME_BUSINESS_PHONE)
  @javax.annotation.Nullable
  private String businessPhone;

  /**
   * Business category
   */
  @JsonAdapter(BusinessTypeEnum.Adapter.class)
  public enum BusinessTypeEnum {
    FOOD("food"),
    
    RETAIL("retail");

    private String value;

    BusinessTypeEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static BusinessTypeEnum fromValue(String value) {
      for (BusinessTypeEnum b : BusinessTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<BusinessTypeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final BusinessTypeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public BusinessTypeEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return BusinessTypeEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      BusinessTypeEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_BUSINESS_TYPE = "businessType";
  @SerializedName(SERIALIZED_NAME_BUSINESS_TYPE)
  @javax.annotation.Nullable
  private BusinessTypeEnum businessType;

  /**
   * Account status (active/suspended/pending derived client-side)
   */
  @JsonAdapter(StatusEnum.Adapter.class)
  public enum StatusEnum {
    PENDING_ACTIVATION("PENDING_ACTIVATION"),
    
    PENDING_PASSWORD_SETUP("PENDING_PASSWORD_SETUP"),
    
    ACTIVE("ACTIVE"),
    
    SUSPENDED("SUSPENDED");

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static StatusEnum fromValue(String value) {
      for (StatusEnum b : StatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<StatusEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final StatusEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public StatusEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return StatusEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      StatusEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  @javax.annotation.Nullable
  private StatusEnum status;

  /**
   * How the merchant was onboarded
   */
  @JsonAdapter(OriginEnum.Adapter.class)
  public enum OriginEnum {
    SELF("SELF"),
    
    PARTNER_API("PARTNER_API"),
    
    ADMIN("ADMIN"),
    
    SSO("SSO");

    private String value;

    OriginEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static OriginEnum fromValue(String value) {
      for (OriginEnum b : OriginEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<OriginEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final OriginEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public OriginEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return OriginEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      OriginEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_ORIGIN = "origin";
  @SerializedName(SERIALIZED_NAME_ORIGIN)
  @javax.annotation.Nullable
  private OriginEnum origin;

  public static final String SERIALIZED_NAME_PARTNER_ID = "partnerId";
  @SerializedName(SERIALIZED_NAME_PARTNER_ID)
  @javax.annotation.Nullable
  private UUID partnerId;

  public static final String SERIALIZED_NAME_REFERRAL_CODE = "referralCode";
  @SerializedName(SERIALIZED_NAME_REFERRAL_CODE)
  @javax.annotation.Nullable
  private String referralCode;

  public static final String SERIALIZED_NAME_REFERRER_USER_ID = "referrerUserId";
  @SerializedName(SERIALIZED_NAME_REFERRER_USER_ID)
  @javax.annotation.Nullable
  private UUID referrerUserId;

  public static final String SERIALIZED_NAME_ADDRESS_HE = "addressHe";
  @SerializedName(SERIALIZED_NAME_ADDRESS_HE)
  @javax.annotation.Nullable
  private String addressHe;

  public static final String SERIALIZED_NAME_ADDRESS_EN = "addressEn";
  @SerializedName(SERIALIZED_NAME_ADDRESS_EN)
  @javax.annotation.Nullable
  private String addressEn;

  public static final String SERIALIZED_NAME_CITY_HE = "cityHe";
  @SerializedName(SERIALIZED_NAME_CITY_HE)
  @javax.annotation.Nullable
  private String cityHe;

  public static final String SERIALIZED_NAME_CITY_EN = "cityEn";
  @SerializedName(SERIALIZED_NAME_CITY_EN)
  @javax.annotation.Nullable
  private String cityEn;

  public static final String SERIALIZED_NAME_LAT = "lat";
  @SerializedName(SERIALIZED_NAME_LAT)
  @javax.annotation.Nullable
  private Double lat;

  public static final String SERIALIZED_NAME_LNG = "lng";
  @SerializedName(SERIALIZED_NAME_LNG)
  @javax.annotation.Nullable
  private Double lng;

  public static final String SERIALIZED_NAME_CREATED_AT = "createdAt";
  @SerializedName(SERIALIZED_NAME_CREATED_AT)
  @javax.annotation.Nullable
  private OffsetDateTime createdAt;

  public static final String SERIALIZED_NAME_LAST_MODIFIED_AT = "lastModifiedAt";
  @SerializedName(SERIALIZED_NAME_LAST_MODIFIED_AT)
  @javax.annotation.Nullable
  private OffsetDateTime lastModifiedAt;

  public MerchantDetail() {
  }

  public MerchantDetail id(@javax.annotation.Nullable UUID id) {
    this.id = id;
    return this;
  }

  /**
   * Unique identifier of the merchant
   * @return id
   */
  @javax.annotation.Nullable
  public UUID getId() {
    return id;
  }

  public void setId(@javax.annotation.Nullable UUID id) {
    this.id = id;
  }


  public MerchantDetail nameHe(@javax.annotation.Nullable String nameHe) {
    this.nameHe = nameHe;
    return this;
  }

  /**
   * Hebrew business name
   * @return nameHe
   */
  @javax.annotation.Nullable
  public String getNameHe() {
    return nameHe;
  }

  public void setNameHe(@javax.annotation.Nullable String nameHe) {
    this.nameHe = nameHe;
  }


  public MerchantDetail nameEn(@javax.annotation.Nullable String nameEn) {
    this.nameEn = nameEn;
    return this;
  }

  /**
   * English business name
   * @return nameEn
   */
  @javax.annotation.Nullable
  public String getNameEn() {
    return nameEn;
  }

  public void setNameEn(@javax.annotation.Nullable String nameEn) {
    this.nameEn = nameEn;
  }


  public MerchantDetail businessName(@javax.annotation.Nullable String businessName) {
    this.businessName = businessName;
    return this;
  }

  /**
   * Legacy/canonical business name
   * @return businessName
   */
  @javax.annotation.Nullable
  public String getBusinessName() {
    return businessName;
  }

  public void setBusinessName(@javax.annotation.Nullable String businessName) {
    this.businessName = businessName;
  }


  public MerchantDetail ownerHe(@javax.annotation.Nullable String ownerHe) {
    this.ownerHe = ownerHe;
    return this;
  }

  /**
   * Owner full name (Hebrew display)
   * @return ownerHe
   */
  @javax.annotation.Nullable
  public String getOwnerHe() {
    return ownerHe;
  }

  public void setOwnerHe(@javax.annotation.Nullable String ownerHe) {
    this.ownerHe = ownerHe;
  }


  public MerchantDetail ownerEn(@javax.annotation.Nullable String ownerEn) {
    this.ownerEn = ownerEn;
    return this;
  }

  /**
   * Owner full name (English display)
   * @return ownerEn
   */
  @javax.annotation.Nullable
  public String getOwnerEn() {
    return ownerEn;
  }

  public void setOwnerEn(@javax.annotation.Nullable String ownerEn) {
    this.ownerEn = ownerEn;
  }


  public MerchantDetail email(@javax.annotation.Nullable String email) {
    this.email = email;
    return this;
  }

  /**
   * Owner account email
   * @return email
   */
  @javax.annotation.Nullable
  public String getEmail() {
    return email;
  }

  public void setEmail(@javax.annotation.Nullable String email) {
    this.email = email;
  }


  public MerchantDetail businessEmail(@javax.annotation.Nullable String businessEmail) {
    this.businessEmail = businessEmail;
    return this;
  }

  /**
   * Public-facing business email
   * @return businessEmail
   */
  @javax.annotation.Nullable
  public String getBusinessEmail() {
    return businessEmail;
  }

  public void setBusinessEmail(@javax.annotation.Nullable String businessEmail) {
    this.businessEmail = businessEmail;
  }


  public MerchantDetail businessPhone(@javax.annotation.Nullable String businessPhone) {
    this.businessPhone = businessPhone;
    return this;
  }

  /**
   * Business phone
   * @return businessPhone
   */
  @javax.annotation.Nullable
  public String getBusinessPhone() {
    return businessPhone;
  }

  public void setBusinessPhone(@javax.annotation.Nullable String businessPhone) {
    this.businessPhone = businessPhone;
  }


  public MerchantDetail businessType(@javax.annotation.Nullable BusinessTypeEnum businessType) {
    this.businessType = businessType;
    return this;
  }

  /**
   * Business category
   * @return businessType
   */
  @javax.annotation.Nullable
  public BusinessTypeEnum getBusinessType() {
    return businessType;
  }

  public void setBusinessType(@javax.annotation.Nullable BusinessTypeEnum businessType) {
    this.businessType = businessType;
  }


  public MerchantDetail status(@javax.annotation.Nullable StatusEnum status) {
    this.status = status;
    return this;
  }

  /**
   * Account status (active/suspended/pending derived client-side)
   * @return status
   */
  @javax.annotation.Nullable
  public StatusEnum getStatus() {
    return status;
  }

  public void setStatus(@javax.annotation.Nullable StatusEnum status) {
    this.status = status;
  }


  public MerchantDetail origin(@javax.annotation.Nullable OriginEnum origin) {
    this.origin = origin;
    return this;
  }

  /**
   * How the merchant was onboarded
   * @return origin
   */
  @javax.annotation.Nullable
  public OriginEnum getOrigin() {
    return origin;
  }

  public void setOrigin(@javax.annotation.Nullable OriginEnum origin) {
    this.origin = origin;
  }


  public MerchantDetail partnerId(@javax.annotation.Nullable UUID partnerId) {
    this.partnerId = partnerId;
    return this;
  }

  /**
   * Owning partner id, if any
   * @return partnerId
   */
  @javax.annotation.Nullable
  public UUID getPartnerId() {
    return partnerId;
  }

  public void setPartnerId(@javax.annotation.Nullable UUID partnerId) {
    this.partnerId = partnerId;
  }


  public MerchantDetail referralCode(@javax.annotation.Nullable String referralCode) {
    this.referralCode = referralCode;
    return this;
  }

  /**
   * Merchant referral code
   * @return referralCode
   */
  @javax.annotation.Nullable
  public String getReferralCode() {
    return referralCode;
  }

  public void setReferralCode(@javax.annotation.Nullable String referralCode) {
    this.referralCode = referralCode;
  }


  public MerchantDetail referrerUserId(@javax.annotation.Nullable UUID referrerUserId) {
    this.referrerUserId = referrerUserId;
    return this;
  }

  /**
   * Referrer (partner) user id, if any
   * @return referrerUserId
   */
  @javax.annotation.Nullable
  public UUID getReferrerUserId() {
    return referrerUserId;
  }

  public void setReferrerUserId(@javax.annotation.Nullable UUID referrerUserId) {
    this.referrerUserId = referrerUserId;
  }


  public MerchantDetail addressHe(@javax.annotation.Nullable String addressHe) {
    this.addressHe = addressHe;
    return this;
  }

  /**
   * Hebrew address line
   * @return addressHe
   */
  @javax.annotation.Nullable
  public String getAddressHe() {
    return addressHe;
  }

  public void setAddressHe(@javax.annotation.Nullable String addressHe) {
    this.addressHe = addressHe;
  }


  public MerchantDetail addressEn(@javax.annotation.Nullable String addressEn) {
    this.addressEn = addressEn;
    return this;
  }

  /**
   * English address line
   * @return addressEn
   */
  @javax.annotation.Nullable
  public String getAddressEn() {
    return addressEn;
  }

  public void setAddressEn(@javax.annotation.Nullable String addressEn) {
    this.addressEn = addressEn;
  }


  public MerchantDetail cityHe(@javax.annotation.Nullable String cityHe) {
    this.cityHe = cityHe;
    return this;
  }

  /**
   * Hebrew city
   * @return cityHe
   */
  @javax.annotation.Nullable
  public String getCityHe() {
    return cityHe;
  }

  public void setCityHe(@javax.annotation.Nullable String cityHe) {
    this.cityHe = cityHe;
  }


  public MerchantDetail cityEn(@javax.annotation.Nullable String cityEn) {
    this.cityEn = cityEn;
    return this;
  }

  /**
   * English city
   * @return cityEn
   */
  @javax.annotation.Nullable
  public String getCityEn() {
    return cityEn;
  }

  public void setCityEn(@javax.annotation.Nullable String cityEn) {
    this.cityEn = cityEn;
  }


  public MerchantDetail lat(@javax.annotation.Nullable Double lat) {
    this.lat = lat;
    return this;
  }

  /**
   * Latitude
   * @return lat
   */
  @javax.annotation.Nullable
  public Double getLat() {
    return lat;
  }

  public void setLat(@javax.annotation.Nullable Double lat) {
    this.lat = lat;
  }


  public MerchantDetail lng(@javax.annotation.Nullable Double lng) {
    this.lng = lng;
    return this;
  }

  /**
   * Longitude
   * @return lng
   */
  @javax.annotation.Nullable
  public Double getLng() {
    return lng;
  }

  public void setLng(@javax.annotation.Nullable Double lng) {
    this.lng = lng;
  }


  public MerchantDetail createdAt(@javax.annotation.Nullable OffsetDateTime createdAt) {
    this.createdAt = createdAt;
    return this;
  }

  /**
   * Creation timestamp
   * @return createdAt
   */
  @javax.annotation.Nullable
  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(@javax.annotation.Nullable OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }


  public MerchantDetail lastModifiedAt(@javax.annotation.Nullable OffsetDateTime lastModifiedAt) {
    this.lastModifiedAt = lastModifiedAt;
    return this;
  }

  /**
   * Last modification timestamp
   * @return lastModifiedAt
   */
  @javax.annotation.Nullable
  public OffsetDateTime getLastModifiedAt() {
    return lastModifiedAt;
  }

  public void setLastModifiedAt(@javax.annotation.Nullable OffsetDateTime lastModifiedAt) {
    this.lastModifiedAt = lastModifiedAt;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MerchantDetail merchantDetail = (MerchantDetail) o;
    return Objects.equals(this.id, merchantDetail.id) &&
        Objects.equals(this.nameHe, merchantDetail.nameHe) &&
        Objects.equals(this.nameEn, merchantDetail.nameEn) &&
        Objects.equals(this.businessName, merchantDetail.businessName) &&
        Objects.equals(this.ownerHe, merchantDetail.ownerHe) &&
        Objects.equals(this.ownerEn, merchantDetail.ownerEn) &&
        Objects.equals(this.email, merchantDetail.email) &&
        Objects.equals(this.businessEmail, merchantDetail.businessEmail) &&
        Objects.equals(this.businessPhone, merchantDetail.businessPhone) &&
        Objects.equals(this.businessType, merchantDetail.businessType) &&
        Objects.equals(this.status, merchantDetail.status) &&
        Objects.equals(this.origin, merchantDetail.origin) &&
        Objects.equals(this.partnerId, merchantDetail.partnerId) &&
        Objects.equals(this.referralCode, merchantDetail.referralCode) &&
        Objects.equals(this.referrerUserId, merchantDetail.referrerUserId) &&
        Objects.equals(this.addressHe, merchantDetail.addressHe) &&
        Objects.equals(this.addressEn, merchantDetail.addressEn) &&
        Objects.equals(this.cityHe, merchantDetail.cityHe) &&
        Objects.equals(this.cityEn, merchantDetail.cityEn) &&
        Objects.equals(this.lat, merchantDetail.lat) &&
        Objects.equals(this.lng, merchantDetail.lng) &&
        Objects.equals(this.createdAt, merchantDetail.createdAt) &&
        Objects.equals(this.lastModifiedAt, merchantDetail.lastModifiedAt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, nameHe, nameEn, businessName, ownerHe, ownerEn, email, businessEmail, businessPhone, businessType, status, origin, partnerId, referralCode, referrerUserId, addressHe, addressEn, cityHe, cityEn, lat, lng, createdAt, lastModifiedAt);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MerchantDetail {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    nameHe: ").append(toIndentedString(nameHe)).append("\n");
    sb.append("    nameEn: ").append(toIndentedString(nameEn)).append("\n");
    sb.append("    businessName: ").append(toIndentedString(businessName)).append("\n");
    sb.append("    ownerHe: ").append(toIndentedString(ownerHe)).append("\n");
    sb.append("    ownerEn: ").append(toIndentedString(ownerEn)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    businessEmail: ").append(toIndentedString(businessEmail)).append("\n");
    sb.append("    businessPhone: ").append(toIndentedString(businessPhone)).append("\n");
    sb.append("    businessType: ").append(toIndentedString(businessType)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    origin: ").append(toIndentedString(origin)).append("\n");
    sb.append("    partnerId: ").append(toIndentedString(partnerId)).append("\n");
    sb.append("    referralCode: ").append(toIndentedString(referralCode)).append("\n");
    sb.append("    referrerUserId: ").append(toIndentedString(referrerUserId)).append("\n");
    sb.append("    addressHe: ").append(toIndentedString(addressHe)).append("\n");
    sb.append("    addressEn: ").append(toIndentedString(addressEn)).append("\n");
    sb.append("    cityHe: ").append(toIndentedString(cityHe)).append("\n");
    sb.append("    cityEn: ").append(toIndentedString(cityEn)).append("\n");
    sb.append("    lat: ").append(toIndentedString(lat)).append("\n");
    sb.append("    lng: ").append(toIndentedString(lng)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    lastModifiedAt: ").append(toIndentedString(lastModifiedAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("id");
    openapiFields.add("nameHe");
    openapiFields.add("nameEn");
    openapiFields.add("businessName");
    openapiFields.add("ownerHe");
    openapiFields.add("ownerEn");
    openapiFields.add("email");
    openapiFields.add("businessEmail");
    openapiFields.add("businessPhone");
    openapiFields.add("businessType");
    openapiFields.add("status");
    openapiFields.add("origin");
    openapiFields.add("partnerId");
    openapiFields.add("referralCode");
    openapiFields.add("referrerUserId");
    openapiFields.add("addressHe");
    openapiFields.add("addressEn");
    openapiFields.add("cityHe");
    openapiFields.add("cityEn");
    openapiFields.add("lat");
    openapiFields.add("lng");
    openapiFields.add("createdAt");
    openapiFields.add("lastModifiedAt");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to MerchantDetail
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!MerchantDetail.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in MerchantDetail is not found in the empty JSON string", MerchantDetail.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!MerchantDetail.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `MerchantDetail` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("id") != null && !jsonObj.get("id").isJsonNull()) && !jsonObj.get("id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("id").toString()));
      }
      if ((jsonObj.get("nameHe") != null && !jsonObj.get("nameHe").isJsonNull()) && !jsonObj.get("nameHe").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `nameHe` to be a primitive type in the JSON string but got `%s`", jsonObj.get("nameHe").toString()));
      }
      if ((jsonObj.get("nameEn") != null && !jsonObj.get("nameEn").isJsonNull()) && !jsonObj.get("nameEn").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `nameEn` to be a primitive type in the JSON string but got `%s`", jsonObj.get("nameEn").toString()));
      }
      if ((jsonObj.get("businessName") != null && !jsonObj.get("businessName").isJsonNull()) && !jsonObj.get("businessName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `businessName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("businessName").toString()));
      }
      if ((jsonObj.get("ownerHe") != null && !jsonObj.get("ownerHe").isJsonNull()) && !jsonObj.get("ownerHe").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `ownerHe` to be a primitive type in the JSON string but got `%s`", jsonObj.get("ownerHe").toString()));
      }
      if ((jsonObj.get("ownerEn") != null && !jsonObj.get("ownerEn").isJsonNull()) && !jsonObj.get("ownerEn").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `ownerEn` to be a primitive type in the JSON string but got `%s`", jsonObj.get("ownerEn").toString()));
      }
      if ((jsonObj.get("email") != null && !jsonObj.get("email").isJsonNull()) && !jsonObj.get("email").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `email` to be a primitive type in the JSON string but got `%s`", jsonObj.get("email").toString()));
      }
      if ((jsonObj.get("businessEmail") != null && !jsonObj.get("businessEmail").isJsonNull()) && !jsonObj.get("businessEmail").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `businessEmail` to be a primitive type in the JSON string but got `%s`", jsonObj.get("businessEmail").toString()));
      }
      if ((jsonObj.get("businessPhone") != null && !jsonObj.get("businessPhone").isJsonNull()) && !jsonObj.get("businessPhone").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `businessPhone` to be a primitive type in the JSON string but got `%s`", jsonObj.get("businessPhone").toString()));
      }
      if ((jsonObj.get("businessType") != null && !jsonObj.get("businessType").isJsonNull()) && !jsonObj.get("businessType").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `businessType` to be a primitive type in the JSON string but got `%s`", jsonObj.get("businessType").toString()));
      }
      // validate the optional field `businessType`
      if (jsonObj.get("businessType") != null && !jsonObj.get("businessType").isJsonNull()) {
        BusinessTypeEnum.validateJsonElement(jsonObj.get("businessType"));
      }
      if ((jsonObj.get("status") != null && !jsonObj.get("status").isJsonNull()) && !jsonObj.get("status").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `status` to be a primitive type in the JSON string but got `%s`", jsonObj.get("status").toString()));
      }
      // validate the optional field `status`
      if (jsonObj.get("status") != null && !jsonObj.get("status").isJsonNull()) {
        StatusEnum.validateJsonElement(jsonObj.get("status"));
      }
      if ((jsonObj.get("origin") != null && !jsonObj.get("origin").isJsonNull()) && !jsonObj.get("origin").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `origin` to be a primitive type in the JSON string but got `%s`", jsonObj.get("origin").toString()));
      }
      // validate the optional field `origin`
      if (jsonObj.get("origin") != null && !jsonObj.get("origin").isJsonNull()) {
        OriginEnum.validateJsonElement(jsonObj.get("origin"));
      }
      if ((jsonObj.get("partnerId") != null && !jsonObj.get("partnerId").isJsonNull()) && !jsonObj.get("partnerId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `partnerId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("partnerId").toString()));
      }
      if ((jsonObj.get("referralCode") != null && !jsonObj.get("referralCode").isJsonNull()) && !jsonObj.get("referralCode").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `referralCode` to be a primitive type in the JSON string but got `%s`", jsonObj.get("referralCode").toString()));
      }
      if ((jsonObj.get("referrerUserId") != null && !jsonObj.get("referrerUserId").isJsonNull()) && !jsonObj.get("referrerUserId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `referrerUserId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("referrerUserId").toString()));
      }
      if ((jsonObj.get("addressHe") != null && !jsonObj.get("addressHe").isJsonNull()) && !jsonObj.get("addressHe").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `addressHe` to be a primitive type in the JSON string but got `%s`", jsonObj.get("addressHe").toString()));
      }
      if ((jsonObj.get("addressEn") != null && !jsonObj.get("addressEn").isJsonNull()) && !jsonObj.get("addressEn").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `addressEn` to be a primitive type in the JSON string but got `%s`", jsonObj.get("addressEn").toString()));
      }
      if ((jsonObj.get("cityHe") != null && !jsonObj.get("cityHe").isJsonNull()) && !jsonObj.get("cityHe").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `cityHe` to be a primitive type in the JSON string but got `%s`", jsonObj.get("cityHe").toString()));
      }
      if ((jsonObj.get("cityEn") != null && !jsonObj.get("cityEn").isJsonNull()) && !jsonObj.get("cityEn").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `cityEn` to be a primitive type in the JSON string but got `%s`", jsonObj.get("cityEn").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!MerchantDetail.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'MerchantDetail' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<MerchantDetail> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(MerchantDetail.class));

       return (TypeAdapter<T>) new TypeAdapter<MerchantDetail>() {
           @Override
           public void write(JsonWriter out, MerchantDetail value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public MerchantDetail read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of MerchantDetail given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of MerchantDetail
   * @throws IOException if the JSON string is invalid with respect to MerchantDetail
   */
  public static MerchantDetail fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, MerchantDetail.class);
  }

  /**
   * Convert an instance of MerchantDetail to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

