/*
 * Zipper Auth API
 * Authentication, OAuth, API keys, and partner/merchant onboarding endpoints exposed via the gateway.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.zipper.auth.sdk.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.zipper.auth.sdk.JSON;

/**
 * Editable merchant profile fields; null fields are left unchanged
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.13.0")
public class MerchantUpdateRequest {
  public static final String SERIALIZED_NAME_NAME_HE = "nameHe";
  @SerializedName(SERIALIZED_NAME_NAME_HE)
  @javax.annotation.Nullable
  private String nameHe;

  public static final String SERIALIZED_NAME_NAME_EN = "nameEn";
  @SerializedName(SERIALIZED_NAME_NAME_EN)
  @javax.annotation.Nullable
  private String nameEn;

  public static final String SERIALIZED_NAME_BUSINESS_NAME = "businessName";
  @SerializedName(SERIALIZED_NAME_BUSINESS_NAME)
  @javax.annotation.Nullable
  private String businessName;

  public static final String SERIALIZED_NAME_BUSINESS_EMAIL = "businessEmail";
  @SerializedName(SERIALIZED_NAME_BUSINESS_EMAIL)
  @javax.annotation.Nullable
  private String businessEmail;

  public static final String SERIALIZED_NAME_BUSINESS_PHONE = "businessPhone";
  @SerializedName(SERIALIZED_NAME_BUSINESS_PHONE)
  @javax.annotation.Nullable
  private String businessPhone;

  /**
   * Gets or Sets businessType
   */
  @JsonAdapter(BusinessTypeEnum.Adapter.class)
  public enum BusinessTypeEnum {
    FOOD("food"),
    
    RETAIL("retail");

    private String value;

    BusinessTypeEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static BusinessTypeEnum fromValue(String value) {
      for (BusinessTypeEnum b : BusinessTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<BusinessTypeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final BusinessTypeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public BusinessTypeEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return BusinessTypeEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      BusinessTypeEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_BUSINESS_TYPE = "businessType";
  @SerializedName(SERIALIZED_NAME_BUSINESS_TYPE)
  @javax.annotation.Nullable
  private BusinessTypeEnum businessType;

  public static final String SERIALIZED_NAME_ADDRESS_HE = "addressHe";
  @SerializedName(SERIALIZED_NAME_ADDRESS_HE)
  @javax.annotation.Nullable
  private String addressHe;

  public static final String SERIALIZED_NAME_ADDRESS_EN = "addressEn";
  @SerializedName(SERIALIZED_NAME_ADDRESS_EN)
  @javax.annotation.Nullable
  private String addressEn;

  public static final String SERIALIZED_NAME_CITY_HE = "cityHe";
  @SerializedName(SERIALIZED_NAME_CITY_HE)
  @javax.annotation.Nullable
  private String cityHe;

  public static final String SERIALIZED_NAME_CITY_EN = "cityEn";
  @SerializedName(SERIALIZED_NAME_CITY_EN)
  @javax.annotation.Nullable
  private String cityEn;

  public static final String SERIALIZED_NAME_LAT = "lat";
  @SerializedName(SERIALIZED_NAME_LAT)
  @javax.annotation.Nullable
  private Double lat;

  public static final String SERIALIZED_NAME_LNG = "lng";
  @SerializedName(SERIALIZED_NAME_LNG)
  @javax.annotation.Nullable
  private Double lng;

  public MerchantUpdateRequest() {
  }

  public MerchantUpdateRequest nameHe(@javax.annotation.Nullable String nameHe) {
    this.nameHe = nameHe;
    return this;
  }

  /**
   * Get nameHe
   * @return nameHe
   */
  @javax.annotation.Nullable
  public String getNameHe() {
    return nameHe;
  }

  public void setNameHe(@javax.annotation.Nullable String nameHe) {
    this.nameHe = nameHe;
  }


  public MerchantUpdateRequest nameEn(@javax.annotation.Nullable String nameEn) {
    this.nameEn = nameEn;
    return this;
  }

  /**
   * Get nameEn
   * @return nameEn
   */
  @javax.annotation.Nullable
  public String getNameEn() {
    return nameEn;
  }

  public void setNameEn(@javax.annotation.Nullable String nameEn) {
    this.nameEn = nameEn;
  }


  public MerchantUpdateRequest businessName(@javax.annotation.Nullable String businessName) {
    this.businessName = businessName;
    return this;
  }

  /**
   * Get businessName
   * @return businessName
   */
  @javax.annotation.Nullable
  public String getBusinessName() {
    return businessName;
  }

  public void setBusinessName(@javax.annotation.Nullable String businessName) {
    this.businessName = businessName;
  }


  public MerchantUpdateRequest businessEmail(@javax.annotation.Nullable String businessEmail) {
    this.businessEmail = businessEmail;
    return this;
  }

  /**
   * Get businessEmail
   * @return businessEmail
   */
  @javax.annotation.Nullable
  public String getBusinessEmail() {
    return businessEmail;
  }

  public void setBusinessEmail(@javax.annotation.Nullable String businessEmail) {
    this.businessEmail = businessEmail;
  }


  public MerchantUpdateRequest businessPhone(@javax.annotation.Nullable String businessPhone) {
    this.businessPhone = businessPhone;
    return this;
  }

  /**
   * Get businessPhone
   * @return businessPhone
   */
  @javax.annotation.Nullable
  public String getBusinessPhone() {
    return businessPhone;
  }

  public void setBusinessPhone(@javax.annotation.Nullable String businessPhone) {
    this.businessPhone = businessPhone;
  }


  public MerchantUpdateRequest businessType(@javax.annotation.Nullable BusinessTypeEnum businessType) {
    this.businessType = businessType;
    return this;
  }

  /**
   * Get businessType
   * @return businessType
   */
  @javax.annotation.Nullable
  public BusinessTypeEnum getBusinessType() {
    return businessType;
  }

  public void setBusinessType(@javax.annotation.Nullable BusinessTypeEnum businessType) {
    this.businessType = businessType;
  }


  public MerchantUpdateRequest addressHe(@javax.annotation.Nullable String addressHe) {
    this.addressHe = addressHe;
    return this;
  }

  /**
   * Get addressHe
   * @return addressHe
   */
  @javax.annotation.Nullable
  public String getAddressHe() {
    return addressHe;
  }

  public void setAddressHe(@javax.annotation.Nullable String addressHe) {
    this.addressHe = addressHe;
  }


  public MerchantUpdateRequest addressEn(@javax.annotation.Nullable String addressEn) {
    this.addressEn = addressEn;
    return this;
  }

  /**
   * Get addressEn
   * @return addressEn
   */
  @javax.annotation.Nullable
  public String getAddressEn() {
    return addressEn;
  }

  public void setAddressEn(@javax.annotation.Nullable String addressEn) {
    this.addressEn = addressEn;
  }


  public MerchantUpdateRequest cityHe(@javax.annotation.Nullable String cityHe) {
    this.cityHe = cityHe;
    return this;
  }

  /**
   * Get cityHe
   * @return cityHe
   */
  @javax.annotation.Nullable
  public String getCityHe() {
    return cityHe;
  }

  public void setCityHe(@javax.annotation.Nullable String cityHe) {
    this.cityHe = cityHe;
  }


  public MerchantUpdateRequest cityEn(@javax.annotation.Nullable String cityEn) {
    this.cityEn = cityEn;
    return this;
  }

  /**
   * Get cityEn
   * @return cityEn
   */
  @javax.annotation.Nullable
  public String getCityEn() {
    return cityEn;
  }

  public void setCityEn(@javax.annotation.Nullable String cityEn) {
    this.cityEn = cityEn;
  }


  public MerchantUpdateRequest lat(@javax.annotation.Nullable Double lat) {
    this.lat = lat;
    return this;
  }

  /**
   * Get lat
   * @return lat
   */
  @javax.annotation.Nullable
  public Double getLat() {
    return lat;
  }

  public void setLat(@javax.annotation.Nullable Double lat) {
    this.lat = lat;
  }


  public MerchantUpdateRequest lng(@javax.annotation.Nullable Double lng) {
    this.lng = lng;
    return this;
  }

  /**
   * Get lng
   * @return lng
   */
  @javax.annotation.Nullable
  public Double getLng() {
    return lng;
  }

  public void setLng(@javax.annotation.Nullable Double lng) {
    this.lng = lng;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MerchantUpdateRequest merchantUpdateRequest = (MerchantUpdateRequest) o;
    return Objects.equals(this.nameHe, merchantUpdateRequest.nameHe) &&
        Objects.equals(this.nameEn, merchantUpdateRequest.nameEn) &&
        Objects.equals(this.businessName, merchantUpdateRequest.businessName) &&
        Objects.equals(this.businessEmail, merchantUpdateRequest.businessEmail) &&
        Objects.equals(this.businessPhone, merchantUpdateRequest.businessPhone) &&
        Objects.equals(this.businessType, merchantUpdateRequest.businessType) &&
        Objects.equals(this.addressHe, merchantUpdateRequest.addressHe) &&
        Objects.equals(this.addressEn, merchantUpdateRequest.addressEn) &&
        Objects.equals(this.cityHe, merchantUpdateRequest.cityHe) &&
        Objects.equals(this.cityEn, merchantUpdateRequest.cityEn) &&
        Objects.equals(this.lat, merchantUpdateRequest.lat) &&
        Objects.equals(this.lng, merchantUpdateRequest.lng);
  }

  @Override
  public int hashCode() {
    return Objects.hash(nameHe, nameEn, businessName, businessEmail, businessPhone, businessType, addressHe, addressEn, cityHe, cityEn, lat, lng);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MerchantUpdateRequest {\n");
    sb.append("    nameHe: ").append(toIndentedString(nameHe)).append("\n");
    sb.append("    nameEn: ").append(toIndentedString(nameEn)).append("\n");
    sb.append("    businessName: ").append(toIndentedString(businessName)).append("\n");
    sb.append("    businessEmail: ").append(toIndentedString(businessEmail)).append("\n");
    sb.append("    businessPhone: ").append(toIndentedString(businessPhone)).append("\n");
    sb.append("    businessType: ").append(toIndentedString(businessType)).append("\n");
    sb.append("    addressHe: ").append(toIndentedString(addressHe)).append("\n");
    sb.append("    addressEn: ").append(toIndentedString(addressEn)).append("\n");
    sb.append("    cityHe: ").append(toIndentedString(cityHe)).append("\n");
    sb.append("    cityEn: ").append(toIndentedString(cityEn)).append("\n");
    sb.append("    lat: ").append(toIndentedString(lat)).append("\n");
    sb.append("    lng: ").append(toIndentedString(lng)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("nameHe");
    openapiFields.add("nameEn");
    openapiFields.add("businessName");
    openapiFields.add("businessEmail");
    openapiFields.add("businessPhone");
    openapiFields.add("businessType");
    openapiFields.add("addressHe");
    openapiFields.add("addressEn");
    openapiFields.add("cityHe");
    openapiFields.add("cityEn");
    openapiFields.add("lat");
    openapiFields.add("lng");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to MerchantUpdateRequest
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!MerchantUpdateRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in MerchantUpdateRequest is not found in the empty JSON string", MerchantUpdateRequest.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!MerchantUpdateRequest.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `MerchantUpdateRequest` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("nameHe") != null && !jsonObj.get("nameHe").isJsonNull()) && !jsonObj.get("nameHe").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `nameHe` to be a primitive type in the JSON string but got `%s`", jsonObj.get("nameHe").toString()));
      }
      if ((jsonObj.get("nameEn") != null && !jsonObj.get("nameEn").isJsonNull()) && !jsonObj.get("nameEn").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `nameEn` to be a primitive type in the JSON string but got `%s`", jsonObj.get("nameEn").toString()));
      }
      if ((jsonObj.get("businessName") != null && !jsonObj.get("businessName").isJsonNull()) && !jsonObj.get("businessName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `businessName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("businessName").toString()));
      }
      if ((jsonObj.get("businessEmail") != null && !jsonObj.get("businessEmail").isJsonNull()) && !jsonObj.get("businessEmail").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `businessEmail` to be a primitive type in the JSON string but got `%s`", jsonObj.get("businessEmail").toString()));
      }
      if ((jsonObj.get("businessPhone") != null && !jsonObj.get("businessPhone").isJsonNull()) && !jsonObj.get("businessPhone").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `businessPhone` to be a primitive type in the JSON string but got `%s`", jsonObj.get("businessPhone").toString()));
      }
      if ((jsonObj.get("businessType") != null && !jsonObj.get("businessType").isJsonNull()) && !jsonObj.get("businessType").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `businessType` to be a primitive type in the JSON string but got `%s`", jsonObj.get("businessType").toString()));
      }
      // validate the optional field `businessType`
      if (jsonObj.get("businessType") != null && !jsonObj.get("businessType").isJsonNull()) {
        BusinessTypeEnum.validateJsonElement(jsonObj.get("businessType"));
      }
      if ((jsonObj.get("addressHe") != null && !jsonObj.get("addressHe").isJsonNull()) && !jsonObj.get("addressHe").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `addressHe` to be a primitive type in the JSON string but got `%s`", jsonObj.get("addressHe").toString()));
      }
      if ((jsonObj.get("addressEn") != null && !jsonObj.get("addressEn").isJsonNull()) && !jsonObj.get("addressEn").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `addressEn` to be a primitive type in the JSON string but got `%s`", jsonObj.get("addressEn").toString()));
      }
      if ((jsonObj.get("cityHe") != null && !jsonObj.get("cityHe").isJsonNull()) && !jsonObj.get("cityHe").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `cityHe` to be a primitive type in the JSON string but got `%s`", jsonObj.get("cityHe").toString()));
      }
      if ((jsonObj.get("cityEn") != null && !jsonObj.get("cityEn").isJsonNull()) && !jsonObj.get("cityEn").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `cityEn` to be a primitive type in the JSON string but got `%s`", jsonObj.get("cityEn").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!MerchantUpdateRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'MerchantUpdateRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<MerchantUpdateRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(MerchantUpdateRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<MerchantUpdateRequest>() {
           @Override
           public void write(JsonWriter out, MerchantUpdateRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public MerchantUpdateRequest read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of MerchantUpdateRequest given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of MerchantUpdateRequest
   * @throws IOException if the JSON string is invalid with respect to MerchantUpdateRequest
   */
  public static MerchantUpdateRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, MerchantUpdateRequest.class);
  }

  /**
   * Convert an instance of MerchantUpdateRequest to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

