/*
 * Zipper Auth API
 * Authentication, OAuth, API keys, and partner/merchant onboarding endpoints exposed via the gateway.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.zipper.auth.sdk.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.zipper.auth.sdk.model.Point;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.zipper.auth.sdk.JSON;

/**
 * Active-merchant statistics for the authenticated partner
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.13.0")
public class MerchantStats {
  public static final String SERIALIZED_NAME_ACTIVE = "active";
  @SerializedName(SERIALIZED_NAME_ACTIVE)
  @javax.annotation.Nullable
  private Long active;

  public static final String SERIALIZED_NAME_PREVIOUS_ACTIVE = "previousActive";
  @SerializedName(SERIALIZED_NAME_PREVIOUS_ACTIVE)
  @javax.annotation.Nullable
  private Long previousActive;

  public static final String SERIALIZED_NAME_SERIES = "series";
  @SerializedName(SERIALIZED_NAME_SERIES)
  @javax.annotation.Nullable
  private List<Point> series = new ArrayList<>();

  public MerchantStats() {
  }

  public MerchantStats active(@javax.annotation.Nullable Long active) {
    this.active = active;
    return this;
  }

  /**
   * Number of currently active merchants for this partner
   * @return active
   */
  @javax.annotation.Nullable
  public Long getActive() {
    return active;
  }

  public void setActive(@javax.annotation.Nullable Long active) {
    this.active = active;
  }


  public MerchantStats previousActive(@javax.annotation.Nullable Long previousActive) {
    this.previousActive = previousActive;
    return this;
  }

  /**
   * Active merchants created before the previous-period cutoff (~30 days ago); used as the comparison base for the period-over-period delta
   * @return previousActive
   */
  @javax.annotation.Nullable
  public Long getPreviousActive() {
    return previousActive;
  }

  public void setPreviousActive(@javax.annotation.Nullable Long previousActive) {
    this.previousActive = previousActive;
  }


  public MerchantStats series(@javax.annotation.Nullable List<Point> series) {
    this.series = series;
    return this;
  }

  public MerchantStats addSeriesItem(Point seriesItem) {
    if (this.series == null) {
      this.series = new ArrayList<>();
    }
    this.series.add(seriesItem);
    return this;
  }

  /**
   * Cumulative active-merchant count per day for the last 7 days, oldest first
   * @return series
   */
  @javax.annotation.Nullable
  public List<Point> getSeries() {
    return series;
  }

  public void setSeries(@javax.annotation.Nullable List<Point> series) {
    this.series = series;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MerchantStats merchantStats = (MerchantStats) o;
    return Objects.equals(this.active, merchantStats.active) &&
        Objects.equals(this.previousActive, merchantStats.previousActive) &&
        Objects.equals(this.series, merchantStats.series);
  }

  @Override
  public int hashCode() {
    return Objects.hash(active, previousActive, series);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MerchantStats {\n");
    sb.append("    active: ").append(toIndentedString(active)).append("\n");
    sb.append("    previousActive: ").append(toIndentedString(previousActive)).append("\n");
    sb.append("    series: ").append(toIndentedString(series)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("active");
    openapiFields.add("previousActive");
    openapiFields.add("series");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to MerchantStats
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!MerchantStats.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in MerchantStats is not found in the empty JSON string", MerchantStats.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!MerchantStats.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `MerchantStats` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (jsonObj.get("series") != null && !jsonObj.get("series").isJsonNull()) {
        JsonArray jsonArrayseries = jsonObj.getAsJsonArray("series");
        if (jsonArrayseries != null) {
          // ensure the json data is an array
          if (!jsonObj.get("series").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `series` to be an array in the JSON string but got `%s`", jsonObj.get("series").toString()));
          }

          // validate the optional field `series` (array)
          for (int i = 0; i < jsonArrayseries.size(); i++) {
            Point.validateJsonElement(jsonArrayseries.get(i));
          };
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!MerchantStats.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'MerchantStats' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<MerchantStats> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(MerchantStats.class));

       return (TypeAdapter<T>) new TypeAdapter<MerchantStats>() {
           @Override
           public void write(JsonWriter out, MerchantStats value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public MerchantStats read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of MerchantStats given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of MerchantStats
   * @throws IOException if the JSON string is invalid with respect to MerchantStats
   */
  public static MerchantStats fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, MerchantStats.class);
  }

  /**
   * Convert an instance of MerchantStats to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

