/*
 * Zipper Auth API
 * Authentication, OAuth, API keys, and partner/merchant onboarding endpoints exposed via the gateway.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.zipper.auth.sdk.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.zipper.auth.sdk.JSON;

/**
 * MerchantOnboardingRequest
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.13.0")
public class MerchantOnboardingRequest {
  public static final String SERIALIZED_NAME_FIRST_NAME = "firstName";
  @SerializedName(SERIALIZED_NAME_FIRST_NAME)
  @javax.annotation.Nonnull
  private String firstName;

  public static final String SERIALIZED_NAME_LAST_NAME = "lastName";
  @SerializedName(SERIALIZED_NAME_LAST_NAME)
  @javax.annotation.Nonnull
  private String lastName;

  public static final String SERIALIZED_NAME_BUSINESS_NAME = "businessName";
  @SerializedName(SERIALIZED_NAME_BUSINESS_NAME)
  @javax.annotation.Nonnull
  private String businessName;

  public static final String SERIALIZED_NAME_EMAIL = "email";
  @SerializedName(SERIALIZED_NAME_EMAIL)
  @javax.annotation.Nonnull
  private String email;

  public static final String SERIALIZED_NAME_BUSINESS_EMAIL = "businessEmail";
  @SerializedName(SERIALIZED_NAME_BUSINESS_EMAIL)
  @javax.annotation.Nullable
  private String businessEmail;

  public static final String SERIALIZED_NAME_BUSINESS_PHONE = "businessPhone";
  @SerializedName(SERIALIZED_NAME_BUSINESS_PHONE)
  @javax.annotation.Nullable
  private String businessPhone;

  public static final String SERIALIZED_NAME_BUSINESS_TYPE = "businessType";
  @SerializedName(SERIALIZED_NAME_BUSINESS_TYPE)
  @javax.annotation.Nullable
  private String businessType;

  public static final String SERIALIZED_NAME_ADDRESS = "address";
  @SerializedName(SERIALIZED_NAME_ADDRESS)
  @javax.annotation.Nullable
  private String address;

  public static final String SERIALIZED_NAME_REQUIRE_EMAIL_CONFIRMATION = "requireEmailConfirmation";
  @SerializedName(SERIALIZED_NAME_REQUIRE_EMAIL_CONFIRMATION)
  @javax.annotation.Nullable
  private Boolean requireEmailConfirmation;

  public MerchantOnboardingRequest() {
  }

  public MerchantOnboardingRequest firstName(@javax.annotation.Nonnull String firstName) {
    this.firstName = firstName;
    return this;
  }

  /**
   * Get firstName
   * @return firstName
   */
  @javax.annotation.Nonnull
  public String getFirstName() {
    return firstName;
  }

  public void setFirstName(@javax.annotation.Nonnull String firstName) {
    this.firstName = firstName;
  }


  public MerchantOnboardingRequest lastName(@javax.annotation.Nonnull String lastName) {
    this.lastName = lastName;
    return this;
  }

  /**
   * Get lastName
   * @return lastName
   */
  @javax.annotation.Nonnull
  public String getLastName() {
    return lastName;
  }

  public void setLastName(@javax.annotation.Nonnull String lastName) {
    this.lastName = lastName;
  }


  public MerchantOnboardingRequest businessName(@javax.annotation.Nonnull String businessName) {
    this.businessName = businessName;
    return this;
  }

  /**
   * Get businessName
   * @return businessName
   */
  @javax.annotation.Nonnull
  public String getBusinessName() {
    return businessName;
  }

  public void setBusinessName(@javax.annotation.Nonnull String businessName) {
    this.businessName = businessName;
  }


  public MerchantOnboardingRequest email(@javax.annotation.Nonnull String email) {
    this.email = email;
    return this;
  }

  /**
   * Get email
   * @return email
   */
  @javax.annotation.Nonnull
  public String getEmail() {
    return email;
  }

  public void setEmail(@javax.annotation.Nonnull String email) {
    this.email = email;
  }


  public MerchantOnboardingRequest businessEmail(@javax.annotation.Nullable String businessEmail) {
    this.businessEmail = businessEmail;
    return this;
  }

  /**
   * Get businessEmail
   * @return businessEmail
   */
  @javax.annotation.Nullable
  public String getBusinessEmail() {
    return businessEmail;
  }

  public void setBusinessEmail(@javax.annotation.Nullable String businessEmail) {
    this.businessEmail = businessEmail;
  }


  public MerchantOnboardingRequest businessPhone(@javax.annotation.Nullable String businessPhone) {
    this.businessPhone = businessPhone;
    return this;
  }

  /**
   * Get businessPhone
   * @return businessPhone
   */
  @javax.annotation.Nullable
  public String getBusinessPhone() {
    return businessPhone;
  }

  public void setBusinessPhone(@javax.annotation.Nullable String businessPhone) {
    this.businessPhone = businessPhone;
  }


  public MerchantOnboardingRequest businessType(@javax.annotation.Nullable String businessType) {
    this.businessType = businessType;
    return this;
  }

  /**
   * Get businessType
   * @return businessType
   */
  @javax.annotation.Nullable
  public String getBusinessType() {
    return businessType;
  }

  public void setBusinessType(@javax.annotation.Nullable String businessType) {
    this.businessType = businessType;
  }


  public MerchantOnboardingRequest address(@javax.annotation.Nullable String address) {
    this.address = address;
    return this;
  }

  /**
   * Get address
   * @return address
   */
  @javax.annotation.Nullable
  public String getAddress() {
    return address;
  }

  public void setAddress(@javax.annotation.Nullable String address) {
    this.address = address;
  }


  public MerchantOnboardingRequest requireEmailConfirmation(@javax.annotation.Nullable Boolean requireEmailConfirmation) {
    this.requireEmailConfirmation = requireEmailConfirmation;
    return this;
  }

  /**
   * Get requireEmailConfirmation
   * @return requireEmailConfirmation
   */
  @javax.annotation.Nullable
  public Boolean getRequireEmailConfirmation() {
    return requireEmailConfirmation;
  }

  public void setRequireEmailConfirmation(@javax.annotation.Nullable Boolean requireEmailConfirmation) {
    this.requireEmailConfirmation = requireEmailConfirmation;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MerchantOnboardingRequest merchantOnboardingRequest = (MerchantOnboardingRequest) o;
    return Objects.equals(this.firstName, merchantOnboardingRequest.firstName) &&
        Objects.equals(this.lastName, merchantOnboardingRequest.lastName) &&
        Objects.equals(this.businessName, merchantOnboardingRequest.businessName) &&
        Objects.equals(this.email, merchantOnboardingRequest.email) &&
        Objects.equals(this.businessEmail, merchantOnboardingRequest.businessEmail) &&
        Objects.equals(this.businessPhone, merchantOnboardingRequest.businessPhone) &&
        Objects.equals(this.businessType, merchantOnboardingRequest.businessType) &&
        Objects.equals(this.address, merchantOnboardingRequest.address) &&
        Objects.equals(this.requireEmailConfirmation, merchantOnboardingRequest.requireEmailConfirmation);
  }

  @Override
  public int hashCode() {
    return Objects.hash(firstName, lastName, businessName, email, businessEmail, businessPhone, businessType, address, requireEmailConfirmation);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MerchantOnboardingRequest {\n");
    sb.append("    firstName: ").append(toIndentedString(firstName)).append("\n");
    sb.append("    lastName: ").append(toIndentedString(lastName)).append("\n");
    sb.append("    businessName: ").append(toIndentedString(businessName)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    businessEmail: ").append(toIndentedString(businessEmail)).append("\n");
    sb.append("    businessPhone: ").append(toIndentedString(businessPhone)).append("\n");
    sb.append("    businessType: ").append(toIndentedString(businessType)).append("\n");
    sb.append("    address: ").append(toIndentedString(address)).append("\n");
    sb.append("    requireEmailConfirmation: ").append(toIndentedString(requireEmailConfirmation)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("firstName");
    openapiFields.add("lastName");
    openapiFields.add("businessName");
    openapiFields.add("email");
    openapiFields.add("businessEmail");
    openapiFields.add("businessPhone");
    openapiFields.add("businessType");
    openapiFields.add("address");
    openapiFields.add("requireEmailConfirmation");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("firstName");
    openapiRequiredFields.add("lastName");
    openapiRequiredFields.add("businessName");
    openapiRequiredFields.add("email");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to MerchantOnboardingRequest
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!MerchantOnboardingRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in MerchantOnboardingRequest is not found in the empty JSON string", MerchantOnboardingRequest.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!MerchantOnboardingRequest.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `MerchantOnboardingRequest` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : MerchantOnboardingRequest.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("firstName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `firstName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("firstName").toString()));
      }
      if (!jsonObj.get("lastName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `lastName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("lastName").toString()));
      }
      if (!jsonObj.get("businessName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `businessName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("businessName").toString()));
      }
      if (!jsonObj.get("email").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `email` to be a primitive type in the JSON string but got `%s`", jsonObj.get("email").toString()));
      }
      if ((jsonObj.get("businessEmail") != null && !jsonObj.get("businessEmail").isJsonNull()) && !jsonObj.get("businessEmail").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `businessEmail` to be a primitive type in the JSON string but got `%s`", jsonObj.get("businessEmail").toString()));
      }
      if ((jsonObj.get("businessPhone") != null && !jsonObj.get("businessPhone").isJsonNull()) && !jsonObj.get("businessPhone").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `businessPhone` to be a primitive type in the JSON string but got `%s`", jsonObj.get("businessPhone").toString()));
      }
      if ((jsonObj.get("businessType") != null && !jsonObj.get("businessType").isJsonNull()) && !jsonObj.get("businessType").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `businessType` to be a primitive type in the JSON string but got `%s`", jsonObj.get("businessType").toString()));
      }
      if ((jsonObj.get("address") != null && !jsonObj.get("address").isJsonNull()) && !jsonObj.get("address").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `address` to be a primitive type in the JSON string but got `%s`", jsonObj.get("address").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!MerchantOnboardingRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'MerchantOnboardingRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<MerchantOnboardingRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(MerchantOnboardingRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<MerchantOnboardingRequest>() {
           @Override
           public void write(JsonWriter out, MerchantOnboardingRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public MerchantOnboardingRequest read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of MerchantOnboardingRequest given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of MerchantOnboardingRequest
   * @throws IOException if the JSON string is invalid with respect to MerchantOnboardingRequest
   */
  public static MerchantOnboardingRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, MerchantOnboardingRequest.class);
  }

  /**
   * Convert an instance of MerchantOnboardingRequest to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

