/*
 * Zipper Auth API
 * Authentication, OAuth, API keys, and partner/merchant onboarding endpoints exposed via the gateway.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.zipper.auth.sdk.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.UUID;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.zipper.auth.sdk.JSON;

/**
 * Result of a partner-initiated merchant onboarding, including generated API credentials
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.13.0")
public class PartnerOnboardingResult {
  public static final String SERIALIZED_NAME_MERCHANT_ID = "merchantId";
  @SerializedName(SERIALIZED_NAME_MERCHANT_ID)
  @javax.annotation.Nullable
  private UUID merchantId;

  public static final String SERIALIZED_NAME_API_KEY = "apiKey";
  @SerializedName(SERIALIZED_NAME_API_KEY)
  @javax.annotation.Nullable
  private String apiKey;

  public static final String SERIALIZED_NAME_API_SECRET = "apiSecret";
  @SerializedName(SERIALIZED_NAME_API_SECRET)
  @javax.annotation.Nullable
  private String apiSecret;

  public static final String SERIALIZED_NAME_MESSAGE = "message";
  @SerializedName(SERIALIZED_NAME_MESSAGE)
  @javax.annotation.Nullable
  private String message;

  public PartnerOnboardingResult() {
  }

  public PartnerOnboardingResult merchantId(@javax.annotation.Nullable UUID merchantId) {
    this.merchantId = merchantId;
    return this;
  }

  /**
   * Unique identifier of the newly onboarded merchant
   * @return merchantId
   */
  @javax.annotation.Nullable
  public UUID getMerchantId() {
    return merchantId;
  }

  public void setMerchantId(@javax.annotation.Nullable UUID merchantId) {
    this.merchantId = merchantId;
  }


  public PartnerOnboardingResult apiKey(@javax.annotation.Nullable String apiKey) {
    this.apiKey = apiKey;
    return this;
  }

  /**
   * Generated API key for the merchant
   * @return apiKey
   */
  @javax.annotation.Nullable
  public String getApiKey() {
    return apiKey;
  }

  public void setApiKey(@javax.annotation.Nullable String apiKey) {
    this.apiKey = apiKey;
  }


  public PartnerOnboardingResult apiSecret(@javax.annotation.Nullable String apiSecret) {
    this.apiSecret = apiSecret;
    return this;
  }

  /**
   * Generated API secret for the merchant – only returned once at creation time
   * @return apiSecret
   */
  @javax.annotation.Nullable
  public String getApiSecret() {
    return apiSecret;
  }

  public void setApiSecret(@javax.annotation.Nullable String apiSecret) {
    this.apiSecret = apiSecret;
  }


  public PartnerOnboardingResult message(@javax.annotation.Nullable String message) {
    this.message = message;
    return this;
  }

  /**
   * Human-readable status message about the onboarding result
   * @return message
   */
  @javax.annotation.Nullable
  public String getMessage() {
    return message;
  }

  public void setMessage(@javax.annotation.Nullable String message) {
    this.message = message;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PartnerOnboardingResult partnerOnboardingResult = (PartnerOnboardingResult) o;
    return Objects.equals(this.merchantId, partnerOnboardingResult.merchantId) &&
        Objects.equals(this.apiKey, partnerOnboardingResult.apiKey) &&
        Objects.equals(this.apiSecret, partnerOnboardingResult.apiSecret) &&
        Objects.equals(this.message, partnerOnboardingResult.message);
  }

  @Override
  public int hashCode() {
    return Objects.hash(merchantId, apiKey, apiSecret, message);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PartnerOnboardingResult {\n");
    sb.append("    merchantId: ").append(toIndentedString(merchantId)).append("\n");
    sb.append("    apiKey: ").append(toIndentedString(apiKey)).append("\n");
    sb.append("    apiSecret: ").append(toIndentedString(apiSecret)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("merchantId");
    openapiFields.add("apiKey");
    openapiFields.add("apiSecret");
    openapiFields.add("message");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to PartnerOnboardingResult
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!PartnerOnboardingResult.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in PartnerOnboardingResult is not found in the empty JSON string", PartnerOnboardingResult.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!PartnerOnboardingResult.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `PartnerOnboardingResult` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("merchantId") != null && !jsonObj.get("merchantId").isJsonNull()) && !jsonObj.get("merchantId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `merchantId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("merchantId").toString()));
      }
      if ((jsonObj.get("apiKey") != null && !jsonObj.get("apiKey").isJsonNull()) && !jsonObj.get("apiKey").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `apiKey` to be a primitive type in the JSON string but got `%s`", jsonObj.get("apiKey").toString()));
      }
      if ((jsonObj.get("apiSecret") != null && !jsonObj.get("apiSecret").isJsonNull()) && !jsonObj.get("apiSecret").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `apiSecret` to be a primitive type in the JSON string but got `%s`", jsonObj.get("apiSecret").toString()));
      }
      if ((jsonObj.get("message") != null && !jsonObj.get("message").isJsonNull()) && !jsonObj.get("message").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `message` to be a primitive type in the JSON string but got `%s`", jsonObj.get("message").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!PartnerOnboardingResult.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'PartnerOnboardingResult' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<PartnerOnboardingResult> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(PartnerOnboardingResult.class));

       return (TypeAdapter<T>) new TypeAdapter<PartnerOnboardingResult>() {
           @Override
           public void write(JsonWriter out, PartnerOnboardingResult value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public PartnerOnboardingResult read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of PartnerOnboardingResult given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of PartnerOnboardingResult
   * @throws IOException if the JSON string is invalid with respect to PartnerOnboardingResult
   */
  public static PartnerOnboardingResult fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, PartnerOnboardingResult.class);
  }

  /**
   * Convert an instance of PartnerOnboardingResult to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

