/*
 * Zipper Auth API
 * Authentication, OAuth, API keys, and partner/merchant onboarding endpoints exposed via the gateway.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.zipper.auth.sdk.api;

import com.zipper.auth.sdk.ApiCallback;
import com.zipper.auth.sdk.ApiClient;
import com.zipper.auth.sdk.ApiException;
import com.zipper.auth.sdk.ApiResponse;
import com.zipper.auth.sdk.Configuration;
import com.zipper.auth.sdk.Pair;
import com.zipper.auth.sdk.ProgressRequestBody;
import com.zipper.auth.sdk.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import com.zipper.auth.sdk.model.ApiKeyCreatedResponse;
import com.zipper.auth.sdk.model.ApiKeySummary;
import com.zipper.auth.sdk.model.CreateApiKeyRequest;
import java.util.UUID;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class MerchantApiKeysApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public MerchantApiKeysApi() {
        this(Configuration.getDefaultApiClient());
    }

    public MerchantApiKeysApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for createApiKey
     * @param createApiKeyRequest  (required)
     * @param acceptLanguage Language preference for response content. Supported: en, he (optional, default to en)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> API key created successfully </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid request body </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Unauthorized </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Forbidden – requires MERCHANT role with PASSWORD auth </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call createApiKeyCall(@javax.annotation.Nonnull CreateApiKeyRequest createApiKeyRequest, @javax.annotation.Nullable String acceptLanguage, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = createApiKeyRequest;

        // create path and map variables
        String localVarPath = "/auth/merchants/api-keys";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "*/*"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        if (acceptLanguage != null) {
            localVarHeaderParams.put("Accept-Language", localVarApiClient.parameterToString(acceptLanguage));
        }


        String[] localVarAuthNames = new String[] { "bearerAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call createApiKeyValidateBeforeCall(@javax.annotation.Nonnull CreateApiKeyRequest createApiKeyRequest, @javax.annotation.Nullable String acceptLanguage, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'createApiKeyRequest' is set
        if (createApiKeyRequest == null) {
            throw new ApiException("Missing the required parameter 'createApiKeyRequest' when calling createApiKey(Async)");
        }

        return createApiKeyCall(createApiKeyRequest, acceptLanguage, _callback);

    }

    /**
     * Create a new API key
     * Generates a new API key pair (apiKey and apiSecret) for the authenticated merchant. The apiSecret is only returned once at creation time and cannot be retrieved later.
     * @param createApiKeyRequest  (required)
     * @param acceptLanguage Language preference for response content. Supported: en, he (optional, default to en)
     * @return ApiKeyCreatedResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> API key created successfully </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid request body </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Unauthorized </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Forbidden – requires MERCHANT role with PASSWORD auth </td><td>  -  </td></tr>
     </table>
     */
    public ApiKeyCreatedResponse createApiKey(@javax.annotation.Nonnull CreateApiKeyRequest createApiKeyRequest, @javax.annotation.Nullable String acceptLanguage) throws ApiException {
        ApiResponse<ApiKeyCreatedResponse> localVarResp = createApiKeyWithHttpInfo(createApiKeyRequest, acceptLanguage);
        return localVarResp.getData();
    }

    /**
     * Create a new API key
     * Generates a new API key pair (apiKey and apiSecret) for the authenticated merchant. The apiSecret is only returned once at creation time and cannot be retrieved later.
     * @param createApiKeyRequest  (required)
     * @param acceptLanguage Language preference for response content. Supported: en, he (optional, default to en)
     * @return ApiResponse&lt;ApiKeyCreatedResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> API key created successfully </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid request body </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Unauthorized </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Forbidden – requires MERCHANT role with PASSWORD auth </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<ApiKeyCreatedResponse> createApiKeyWithHttpInfo(@javax.annotation.Nonnull CreateApiKeyRequest createApiKeyRequest, @javax.annotation.Nullable String acceptLanguage) throws ApiException {
        okhttp3.Call localVarCall = createApiKeyValidateBeforeCall(createApiKeyRequest, acceptLanguage, null);
        Type localVarReturnType = new TypeToken<ApiKeyCreatedResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Create a new API key (asynchronously)
     * Generates a new API key pair (apiKey and apiSecret) for the authenticated merchant. The apiSecret is only returned once at creation time and cannot be retrieved later.
     * @param createApiKeyRequest  (required)
     * @param acceptLanguage Language preference for response content. Supported: en, he (optional, default to en)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> API key created successfully </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid request body </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Unauthorized </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Forbidden – requires MERCHANT role with PASSWORD auth </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call createApiKeyAsync(@javax.annotation.Nonnull CreateApiKeyRequest createApiKeyRequest, @javax.annotation.Nullable String acceptLanguage, final ApiCallback<ApiKeyCreatedResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = createApiKeyValidateBeforeCall(createApiKeyRequest, acceptLanguage, _callback);
        Type localVarReturnType = new TypeToken<ApiKeyCreatedResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for listApiKeys
     * @param acceptLanguage Language preference for response content. Supported: en, he (optional, default to en)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> API keys retrieved successfully </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Unauthorized </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Forbidden – requires MERCHANT role with PASSWORD auth </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call listApiKeysCall(@javax.annotation.Nullable String acceptLanguage, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/auth/merchants/api-keys";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "*/*"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        if (acceptLanguage != null) {
            localVarHeaderParams.put("Accept-Language", localVarApiClient.parameterToString(acceptLanguage));
        }


        String[] localVarAuthNames = new String[] { "bearerAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call listApiKeysValidateBeforeCall(@javax.annotation.Nullable String acceptLanguage, final ApiCallback _callback) throws ApiException {
        return listApiKeysCall(acceptLanguage, _callback);

    }

    /**
     * List all API keys
     * Returns a summary of all API keys belonging to the authenticated merchant, including status and usage metadata.
     * @param acceptLanguage Language preference for response content. Supported: en, he (optional, default to en)
     * @return ApiKeySummary
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> API keys retrieved successfully </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Unauthorized </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Forbidden – requires MERCHANT role with PASSWORD auth </td><td>  -  </td></tr>
     </table>
     */
    public ApiKeySummary listApiKeys(@javax.annotation.Nullable String acceptLanguage) throws ApiException {
        ApiResponse<ApiKeySummary> localVarResp = listApiKeysWithHttpInfo(acceptLanguage);
        return localVarResp.getData();
    }

    /**
     * List all API keys
     * Returns a summary of all API keys belonging to the authenticated merchant, including status and usage metadata.
     * @param acceptLanguage Language preference for response content. Supported: en, he (optional, default to en)
     * @return ApiResponse&lt;ApiKeySummary&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> API keys retrieved successfully </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Unauthorized </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Forbidden – requires MERCHANT role with PASSWORD auth </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<ApiKeySummary> listApiKeysWithHttpInfo(@javax.annotation.Nullable String acceptLanguage) throws ApiException {
        okhttp3.Call localVarCall = listApiKeysValidateBeforeCall(acceptLanguage, null);
        Type localVarReturnType = new TypeToken<ApiKeySummary>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * List all API keys (asynchronously)
     * Returns a summary of all API keys belonging to the authenticated merchant, including status and usage metadata.
     * @param acceptLanguage Language preference for response content. Supported: en, he (optional, default to en)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> API keys retrieved successfully </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Unauthorized </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Forbidden – requires MERCHANT role with PASSWORD auth </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call listApiKeysAsync(@javax.annotation.Nullable String acceptLanguage, final ApiCallback<ApiKeySummary> _callback) throws ApiException {

        okhttp3.Call localVarCall = listApiKeysValidateBeforeCall(acceptLanguage, _callback);
        Type localVarReturnType = new TypeToken<ApiKeySummary>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for revokeApiKey
     * @param id API key identifier (required)
     * @param acceptLanguage Language preference for response content. Supported: en, he (optional, default to en)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> API key revoked successfully </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Unauthorized </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Forbidden – requires MERCHANT role with PASSWORD auth </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> API key not found </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call revokeApiKeyCall(@javax.annotation.Nonnull UUID id, @javax.annotation.Nullable String acceptLanguage, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/auth/merchants/api-keys/{id}"
            .replace("{" + "id" + "}", localVarApiClient.escapeString(id.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        if (acceptLanguage != null) {
            localVarHeaderParams.put("Accept-Language", localVarApiClient.parameterToString(acceptLanguage));
        }


        String[] localVarAuthNames = new String[] { "bearerAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "DELETE", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call revokeApiKeyValidateBeforeCall(@javax.annotation.Nonnull UUID id, @javax.annotation.Nullable String acceptLanguage, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException("Missing the required parameter 'id' when calling revokeApiKey(Async)");
        }

        return revokeApiKeyCall(id, acceptLanguage, _callback);

    }

    /**
     * Revoke an API key
     * Permanently revokes the specified API key. The key will no longer be usable for authentication.
     * @param id API key identifier (required)
     * @param acceptLanguage Language preference for response content. Supported: en, he (optional, default to en)
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> API key revoked successfully </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Unauthorized </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Forbidden – requires MERCHANT role with PASSWORD auth </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> API key not found </td><td>  -  </td></tr>
     </table>
     */
    public void revokeApiKey(@javax.annotation.Nonnull UUID id, @javax.annotation.Nullable String acceptLanguage) throws ApiException {
        revokeApiKeyWithHttpInfo(id, acceptLanguage);
    }

    /**
     * Revoke an API key
     * Permanently revokes the specified API key. The key will no longer be usable for authentication.
     * @param id API key identifier (required)
     * @param acceptLanguage Language preference for response content. Supported: en, he (optional, default to en)
     * @return ApiResponse&lt;Void&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> API key revoked successfully </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Unauthorized </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Forbidden – requires MERCHANT role with PASSWORD auth </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> API key not found </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Void> revokeApiKeyWithHttpInfo(@javax.annotation.Nonnull UUID id, @javax.annotation.Nullable String acceptLanguage) throws ApiException {
        okhttp3.Call localVarCall = revokeApiKeyValidateBeforeCall(id, acceptLanguage, null);
        return localVarApiClient.execute(localVarCall);
    }

    /**
     * Revoke an API key (asynchronously)
     * Permanently revokes the specified API key. The key will no longer be usable for authentication.
     * @param id API key identifier (required)
     * @param acceptLanguage Language preference for response content. Supported: en, he (optional, default to en)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> API key revoked successfully </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Unauthorized </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Forbidden – requires MERCHANT role with PASSWORD auth </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> API key not found </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call revokeApiKeyAsync(@javax.annotation.Nonnull UUID id, @javax.annotation.Nullable String acceptLanguage, final ApiCallback<Void> _callback) throws ApiException {

        okhttp3.Call localVarCall = revokeApiKeyValidateBeforeCall(id, acceptLanguage, _callback);
        localVarApiClient.executeAsync(localVarCall, _callback);
        return localVarCall;
    }
}
