/*
 * Zipper Auth API
 * Authentication, OAuth, API keys, and partner/merchant onboarding endpoints exposed via the gateway.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.zipper.auth.sdk.api;

import com.zipper.auth.sdk.ApiCallback;
import com.zipper.auth.sdk.ApiClient;
import com.zipper.auth.sdk.ApiException;
import com.zipper.auth.sdk.ApiResponse;
import com.zipper.auth.sdk.Configuration;
import com.zipper.auth.sdk.Pair;
import com.zipper.auth.sdk.ProgressRequestBody;
import com.zipper.auth.sdk.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import com.zipper.auth.sdk.model.MerchantOnboardingRequest;
import com.zipper.auth.sdk.model.MerchantOnboardingStatus;
import com.zipper.auth.sdk.model.MerchantSummary;
import com.zipper.auth.sdk.model.Pageable;
import com.zipper.auth.sdk.model.PartnerOnboardingResult;
import java.util.UUID;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class PartnerMerchantsApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public PartnerMerchantsApi() {
        this(Configuration.getDefaultApiClient());
    }

    public PartnerMerchantsApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for getPartnerMerchantByEmail
     * @param email Merchant email address (required)
     * @param acceptLanguage Language preference for response content. Supported: en, he (optional, default to en)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Merchant found </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Unauthorized </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Merchant not found for this partner </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getPartnerMerchantByEmailCall(@javax.annotation.Nonnull String email, @javax.annotation.Nullable String acceptLanguage, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/auth/partners/merchants/by-email";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (email != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("email", email));
        }

        final String[] localVarAccepts = {
            "*/*"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        if (acceptLanguage != null) {
            localVarHeaderParams.put("Accept-Language", localVarApiClient.parameterToString(acceptLanguage));
        }


        String[] localVarAuthNames = new String[] { "bearerAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getPartnerMerchantByEmailValidateBeforeCall(@javax.annotation.Nonnull String email, @javax.annotation.Nullable String acceptLanguage, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'email' is set
        if (email == null) {
            throw new ApiException("Missing the required parameter 'email' when calling getPartnerMerchantByEmail(Async)");
        }

        return getPartnerMerchantByEmailCall(email, acceptLanguage, _callback);

    }

    /**
     * Get merchant by email
     * Looks up a merchant by their email address within the authenticated partner&#39;s scope. Returns the merchant summary if found and belongs to this partner.
     * @param email Merchant email address (required)
     * @param acceptLanguage Language preference for response content. Supported: en, he (optional, default to en)
     * @return MerchantSummary
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Merchant found </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Unauthorized </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Merchant not found for this partner </td><td>  -  </td></tr>
     </table>
     */
    public MerchantSummary getPartnerMerchantByEmail(@javax.annotation.Nonnull String email, @javax.annotation.Nullable String acceptLanguage) throws ApiException {
        ApiResponse<MerchantSummary> localVarResp = getPartnerMerchantByEmailWithHttpInfo(email, acceptLanguage);
        return localVarResp.getData();
    }

    /**
     * Get merchant by email
     * Looks up a merchant by their email address within the authenticated partner&#39;s scope. Returns the merchant summary if found and belongs to this partner.
     * @param email Merchant email address (required)
     * @param acceptLanguage Language preference for response content. Supported: en, he (optional, default to en)
     * @return ApiResponse&lt;MerchantSummary&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Merchant found </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Unauthorized </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Merchant not found for this partner </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<MerchantSummary> getPartnerMerchantByEmailWithHttpInfo(@javax.annotation.Nonnull String email, @javax.annotation.Nullable String acceptLanguage) throws ApiException {
        okhttp3.Call localVarCall = getPartnerMerchantByEmailValidateBeforeCall(email, acceptLanguage, null);
        Type localVarReturnType = new TypeToken<MerchantSummary>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Get merchant by email (asynchronously)
     * Looks up a merchant by their email address within the authenticated partner&#39;s scope. Returns the merchant summary if found and belongs to this partner.
     * @param email Merchant email address (required)
     * @param acceptLanguage Language preference for response content. Supported: en, he (optional, default to en)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Merchant found </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Unauthorized </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Merchant not found for this partner </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getPartnerMerchantByEmailAsync(@javax.annotation.Nonnull String email, @javax.annotation.Nullable String acceptLanguage, final ApiCallback<MerchantSummary> _callback) throws ApiException {

        okhttp3.Call localVarCall = getPartnerMerchantByEmailValidateBeforeCall(email, acceptLanguage, _callback);
        Type localVarReturnType = new TypeToken<MerchantSummary>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for getPartnerMerchantStatus
     * @param merchantId Merchant identifier (required)
     * @param acceptLanguage Language preference for response content. Supported: en, he (optional, default to en)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Merchant status retrieved successfully </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Unauthorized </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Forbidden – merchant does not belong to this partner </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Merchant not found </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getPartnerMerchantStatusCall(@javax.annotation.Nonnull UUID merchantId, @javax.annotation.Nullable String acceptLanguage, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/auth/partners/merchants/{merchantId}/status"
            .replace("{" + "merchantId" + "}", localVarApiClient.escapeString(merchantId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "*/*"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        if (acceptLanguage != null) {
            localVarHeaderParams.put("Accept-Language", localVarApiClient.parameterToString(acceptLanguage));
        }


        String[] localVarAuthNames = new String[] { "bearerAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getPartnerMerchantStatusValidateBeforeCall(@javax.annotation.Nonnull UUID merchantId, @javax.annotation.Nullable String acceptLanguage, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'merchantId' is set
        if (merchantId == null) {
            throw new ApiException("Missing the required parameter 'merchantId' when calling getPartnerMerchantStatus(Async)");
        }

        return getPartnerMerchantStatusCall(merchantId, acceptLanguage, _callback);

    }

    /**
     * Get merchant onboarding status
     * Returns the onboarding status of a specific merchant, including account status, email verification state, and creation date. The merchant must belong to the authenticated partner.
     * @param merchantId Merchant identifier (required)
     * @param acceptLanguage Language preference for response content. Supported: en, he (optional, default to en)
     * @return MerchantOnboardingStatus
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Merchant status retrieved successfully </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Unauthorized </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Forbidden – merchant does not belong to this partner </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Merchant not found </td><td>  -  </td></tr>
     </table>
     */
    public MerchantOnboardingStatus getPartnerMerchantStatus(@javax.annotation.Nonnull UUID merchantId, @javax.annotation.Nullable String acceptLanguage) throws ApiException {
        ApiResponse<MerchantOnboardingStatus> localVarResp = getPartnerMerchantStatusWithHttpInfo(merchantId, acceptLanguage);
        return localVarResp.getData();
    }

    /**
     * Get merchant onboarding status
     * Returns the onboarding status of a specific merchant, including account status, email verification state, and creation date. The merchant must belong to the authenticated partner.
     * @param merchantId Merchant identifier (required)
     * @param acceptLanguage Language preference for response content. Supported: en, he (optional, default to en)
     * @return ApiResponse&lt;MerchantOnboardingStatus&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Merchant status retrieved successfully </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Unauthorized </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Forbidden – merchant does not belong to this partner </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Merchant not found </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<MerchantOnboardingStatus> getPartnerMerchantStatusWithHttpInfo(@javax.annotation.Nonnull UUID merchantId, @javax.annotation.Nullable String acceptLanguage) throws ApiException {
        okhttp3.Call localVarCall = getPartnerMerchantStatusValidateBeforeCall(merchantId, acceptLanguage, null);
        Type localVarReturnType = new TypeToken<MerchantOnboardingStatus>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Get merchant onboarding status (asynchronously)
     * Returns the onboarding status of a specific merchant, including account status, email verification state, and creation date. The merchant must belong to the authenticated partner.
     * @param merchantId Merchant identifier (required)
     * @param acceptLanguage Language preference for response content. Supported: en, he (optional, default to en)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Merchant status retrieved successfully </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Unauthorized </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Forbidden – merchant does not belong to this partner </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Merchant not found </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getPartnerMerchantStatusAsync(@javax.annotation.Nonnull UUID merchantId, @javax.annotation.Nullable String acceptLanguage, final ApiCallback<MerchantOnboardingStatus> _callback) throws ApiException {

        okhttp3.Call localVarCall = getPartnerMerchantStatusValidateBeforeCall(merchantId, acceptLanguage, _callback);
        Type localVarReturnType = new TypeToken<MerchantOnboardingStatus>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for listPartnerMerchants
     * @param pageable  (required)
     * @param acceptLanguage Language preference for response content. Supported: en, he (optional, default to en)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Merchants retrieved successfully </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Unauthorized </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Partner not found </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call listPartnerMerchantsCall(@javax.annotation.Nonnull Pageable pageable, @javax.annotation.Nullable String acceptLanguage, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/auth/partners/merchants";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (pageable != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("pageable", pageable));
        }

        final String[] localVarAccepts = {
            "*/*"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        if (acceptLanguage != null) {
            localVarHeaderParams.put("Accept-Language", localVarApiClient.parameterToString(acceptLanguage));
        }


        String[] localVarAuthNames = new String[] { "bearerAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call listPartnerMerchantsValidateBeforeCall(@javax.annotation.Nonnull Pageable pageable, @javax.annotation.Nullable String acceptLanguage, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'pageable' is set
        if (pageable == null) {
            throw new ApiException("Missing the required parameter 'pageable' when calling listPartnerMerchants(Async)");
        }

        return listPartnerMerchantsCall(pageable, acceptLanguage, _callback);

    }

    /**
     * List partner merchants
     * Returns a paginated list of all merchants onboarded by the authenticated partner, including their business name, email, status, and onboarding origin.
     * @param pageable  (required)
     * @param acceptLanguage Language preference for response content. Supported: en, he (optional, default to en)
     * @return MerchantSummary
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Merchants retrieved successfully </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Unauthorized </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Partner not found </td><td>  -  </td></tr>
     </table>
     */
    public MerchantSummary listPartnerMerchants(@javax.annotation.Nonnull Pageable pageable, @javax.annotation.Nullable String acceptLanguage) throws ApiException {
        ApiResponse<MerchantSummary> localVarResp = listPartnerMerchantsWithHttpInfo(pageable, acceptLanguage);
        return localVarResp.getData();
    }

    /**
     * List partner merchants
     * Returns a paginated list of all merchants onboarded by the authenticated partner, including their business name, email, status, and onboarding origin.
     * @param pageable  (required)
     * @param acceptLanguage Language preference for response content. Supported: en, he (optional, default to en)
     * @return ApiResponse&lt;MerchantSummary&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Merchants retrieved successfully </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Unauthorized </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Partner not found </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<MerchantSummary> listPartnerMerchantsWithHttpInfo(@javax.annotation.Nonnull Pageable pageable, @javax.annotation.Nullable String acceptLanguage) throws ApiException {
        okhttp3.Call localVarCall = listPartnerMerchantsValidateBeforeCall(pageable, acceptLanguage, null);
        Type localVarReturnType = new TypeToken<MerchantSummary>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * List partner merchants (asynchronously)
     * Returns a paginated list of all merchants onboarded by the authenticated partner, including their business name, email, status, and onboarding origin.
     * @param pageable  (required)
     * @param acceptLanguage Language preference for response content. Supported: en, he (optional, default to en)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Merchants retrieved successfully </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Unauthorized </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Partner not found </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call listPartnerMerchantsAsync(@javax.annotation.Nonnull Pageable pageable, @javax.annotation.Nullable String acceptLanguage, final ApiCallback<MerchantSummary> _callback) throws ApiException {

        okhttp3.Call localVarCall = listPartnerMerchantsValidateBeforeCall(pageable, acceptLanguage, _callback);
        Type localVarReturnType = new TypeToken<MerchantSummary>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for partnerOnboardMerchant
     * @param merchantOnboardingRequest  (required)
     * @param acceptLanguage Language preference for response content. Supported: en, he (optional, default to en)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Merchant onboarded successfully </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid request body </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Unauthorized </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Partner not found </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call partnerOnboardMerchantCall(@javax.annotation.Nonnull MerchantOnboardingRequest merchantOnboardingRequest, @javax.annotation.Nullable String acceptLanguage, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = merchantOnboardingRequest;

        // create path and map variables
        String localVarPath = "/auth/partners/merchants";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "*/*"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        if (acceptLanguage != null) {
            localVarHeaderParams.put("Accept-Language", localVarApiClient.parameterToString(acceptLanguage));
        }


        String[] localVarAuthNames = new String[] { "bearerAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call partnerOnboardMerchantValidateBeforeCall(@javax.annotation.Nonnull MerchantOnboardingRequest merchantOnboardingRequest, @javax.annotation.Nullable String acceptLanguage, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'merchantOnboardingRequest' is set
        if (merchantOnboardingRequest == null) {
            throw new ApiException("Missing the required parameter 'merchantOnboardingRequest' when calling partnerOnboardMerchant(Async)");
        }

        return partnerOnboardMerchantCall(merchantOnboardingRequest, acceptLanguage, _callback);

    }

    /**
     * Onboard a new merchant
     * Creates and onboards a new merchant under the authenticated partner. The merchant will receive an activation email to complete registration.
     * @param merchantOnboardingRequest  (required)
     * @param acceptLanguage Language preference for response content. Supported: en, he (optional, default to en)
     * @return PartnerOnboardingResult
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Merchant onboarded successfully </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid request body </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Unauthorized </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Partner not found </td><td>  -  </td></tr>
     </table>
     */
    public PartnerOnboardingResult partnerOnboardMerchant(@javax.annotation.Nonnull MerchantOnboardingRequest merchantOnboardingRequest, @javax.annotation.Nullable String acceptLanguage) throws ApiException {
        ApiResponse<PartnerOnboardingResult> localVarResp = partnerOnboardMerchantWithHttpInfo(merchantOnboardingRequest, acceptLanguage);
        return localVarResp.getData();
    }

    /**
     * Onboard a new merchant
     * Creates and onboards a new merchant under the authenticated partner. The merchant will receive an activation email to complete registration.
     * @param merchantOnboardingRequest  (required)
     * @param acceptLanguage Language preference for response content. Supported: en, he (optional, default to en)
     * @return ApiResponse&lt;PartnerOnboardingResult&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Merchant onboarded successfully </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid request body </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Unauthorized </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Partner not found </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<PartnerOnboardingResult> partnerOnboardMerchantWithHttpInfo(@javax.annotation.Nonnull MerchantOnboardingRequest merchantOnboardingRequest, @javax.annotation.Nullable String acceptLanguage) throws ApiException {
        okhttp3.Call localVarCall = partnerOnboardMerchantValidateBeforeCall(merchantOnboardingRequest, acceptLanguage, null);
        Type localVarReturnType = new TypeToken<PartnerOnboardingResult>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Onboard a new merchant (asynchronously)
     * Creates and onboards a new merchant under the authenticated partner. The merchant will receive an activation email to complete registration.
     * @param merchantOnboardingRequest  (required)
     * @param acceptLanguage Language preference for response content. Supported: en, he (optional, default to en)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Merchant onboarded successfully </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid request body </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Unauthorized </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Partner not found </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call partnerOnboardMerchantAsync(@javax.annotation.Nonnull MerchantOnboardingRequest merchantOnboardingRequest, @javax.annotation.Nullable String acceptLanguage, final ApiCallback<PartnerOnboardingResult> _callback) throws ApiException {

        okhttp3.Call localVarCall = partnerOnboardMerchantValidateBeforeCall(merchantOnboardingRequest, acceptLanguage, _callback);
        Type localVarReturnType = new TypeToken<PartnerOnboardingResult>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
